### ISSUE TITLE
Performance slows significantly when stats panel is up

### ISSUE THREAD

**Issue by thedoc31** [mattsemar/dsp-bottleneck#1]
Hi, I gave bottleneck a try today because I'm _so_ tired of clicking on every planet and system in the stats panel to try to figure out where things are being made and trying to divine where my bottlenecks are. So excited to see this mod!

Unfortunately with the stats panel up, it dropped FPS to ~11 every few seconds while it reloaded the data. Closing the stats panel returned regular performance to the game. Might be something with the calculations or volume of lookups occurring - my build is large and growing. BetterStats alone does not affect DSP this way. 

If it makes any difference, I have two dyson spheres in two different systems; in my "home" system I have three layers, one of which has full solar sail panels; the others do not. 

If you need a copy of my save game to test with I can send it over to you. It's about 500MB. Let me know if you need any other information. 

System specs:
Core i7-8700K
16GB RAM
EVGA GeForce 2070 SUPER (stock), game ready drivers 496.76
Windows 10 21H1

**Comment by mattsemar** [comment]
So does the game become unresponsive or is it just a drop in FPS?

**Comment by mattsemar** [comment]
@thedoc31 about how many planets would you say you are producing stuff on? If the slowdown is affecting the gameplay then I think it would be good to get a copy of your savefile, and if there are mods that I would need installed to load it up then either a modlist or, if you're using r2modman, the code from "Export profile as code"

**Comment by mattsemar** [comment]
I made a few tweaks today that I think will help. Let me know if you still see issues after v0.1.1

**Comment by thedoc31** [comment]
> @thedoc31 about how many planets would you say you are producing stuff on? If the slowdown is affecting the gameplay then I think it would be good to get a copy of your savefile, and if there are mods that I would need installed to load it up then either a modlist or, if you're using r2modman, the code from "Export profile as code"

I only use BetterStats as far as mods are concerned. I would estimate at least 40 planets, maybe more. The game itself continues to run in the background while stats panel is up. The functionality of the game while stats is up is pretty limited anyway so I usually close the panel before moving onto the next activity. Will give the new version a try tonight!

**Comment by thedoc31** [comment]
It's definitely better than it was, but my FPS still drops between 25-27 when I have the "Entire Star Cluster" selected. If I flip that to "local planet" or click through star systems the issue does not appear anymore. Similarly, closing the dialog makes the FPS issue go away. 

I sent a Google Drive sharing link with a copy of the save file (~250MB zip) to the email listed on your github profile. Let me know if you aren't able to download it.

**Comment by mattsemar** [comment]
Ok, thanks for the savefile I was able to load it up. I only get like 13/27 outside of stats window but around 9/20 with stats open. I think it actually is happening because of the interaction between my mod & BetterStats (even though it doesn't happen with only BetterStats). The problem is that BetterStats runs on every `Update` and interacts with a lot of the same things that Bottleneck does. ~I actually had opened a PR for BetterStats that makes it run only 1 / 10 Updates, but it's still sitting there. https://github.com/DysonSphereMod/QOL/pull/123~

~If you go to that PR there is a link to a replacement BetterStats.dll that you should be able to just drop into the same folder where the mod manager installs it.~
```
C:\Users\USERNAME\AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\default\BepInEx\plugins\brokenmass-BetterStats
```

Can you try again with the latest version of BetterStats and let me know if it helps?

**Comment by mattsemar** [comment]
Well, turns out that PR I opened got merged so you can test my hypothesis just by updating to the latest version of BetterStats

**Comment by thedoc31** [comment]
Well that's convenient! Yes, it does help. When not in my home system, I do see occasional flashes down to 25|55 while the stats panel is on "Entire Star Cluster" and sometimes a really quick initial FPS drop flash if I drill down to look at stats system by system, but it does not stay constant like it did previously. Definitely more usable now.

When on my home planet (Beta Leonis Minoris IV), I'm seeing occasional orange "Lag" messages underneath the FPS counter that I've never seen before. Without stats panel up, I hover between 22-25|43-45, but when it's up I see an initial drop to 10 FPS for a couple seconds with a "Lag" message, then it just hovers between 18-21|39-41.

Unmodded with the stats panel up I see 20-23|44-48 so it's not a huge difference but noticeable at these already-terrible framerates. lol

**Comment by mattsemar** [comment]
Ok, I think that's about as good as we can do on this one

**Comment by thedoc31** [comment]
Agreed, thank you!
