### ISSUE TITLE
New update causes an error on start

### ISSUE THREAD

**Issue by KironaDragryph** [mattsemar/dsp-bottleneck#3]
![image](https://user-images.githubusercontent.com/31082532/164580116-e8ba376b-81c1-4cf2-ac6a-562b4a721426.png)

NullReferenceException: Object reference not set to an instance of an object
Bottleneck.Stats.BetterStats.Awake() (at <6410c4ea9fd848038d5b93a48c5091d7>:0)
UnityEngine.GameObject:AddComponent()
Bottleneck.BottleneckPlugin:ConditionallyLoadStats()
Bottleneck.BottleneckPlugin:Update()

I do not have the BetterStats mod enabled, though I see "BetterStats" mentioned in this error.

**Comment by mattsemar** [comment]
This is with version 1.0.7?

**Comment by mattsemar** [comment]
If so, can you please try the patch for CommonAPI that Raptor put in discord (assuming there's not an official release of CommonAPI yet)? https://discord.com/channels/@me/966879863556431882/966892306055700511

**Comment by KironaDragryph** [comment]
Apologies for the slow response, life and all. This did occur with the 1.0.7 update, however the update to CommonAPI appears to have fixed it. I no longer have any bugs that I can find with your mod active. Sorry for the bother ^^;

**Comment by mattsemar** [comment]
It's no bother, and I'm glad everything is working now
