### ISSUE TITLE
Request support for multiple languages

### ISSUE THREAD

**Issue by Ximu-Luya** [mattsemar/dsp-bottleneck#6]
My game language is Chinese, but the UI added by the mod is in English. Although I can understand English, I think it is not harmonious.
I hope you can support multi-language display, and I am willing to contribute UI translation in Chinese

**Comment by mattsemar** [comment]
That's great, thanks for volunteering translations. If you give me translations for the these labels, "Producers", "Consumers" and "Theoretical max" I can get started on extracting all the text in the mod

**Comment by mattsemar** [comment]
Ok, I started working on adding multiple language support. Please take a look at the values I got from Google Translate and let me know what the correct values should be (I'm sure they are pretty bad right now): 

https://github.com/mattsemar/dsp-bottleneck/blob/955ee1577919e4c8ff5d7107aacbc3d188e4740b/UI/Strings.cs

So, for example, on this line: 
```
            ProtoRegistry.RegisterString("missingSprayLabel", "Missing spray", "缺少喷雾");
```
If it should be "缺少增殖物", you can just put something like this:

missingSprayLabel,缺少增殖物

Also, I uploaded a pre-release version with the machine generated translations here: https://github.com/mattsemar/dsp-bottleneck/releases/tag/v1.0.14-translate - It should be helpful in spotting text that I missed altogether when I was searching for strings to localize.

**Comment by Ximu-Luya** [comment]
No problem, I'll check it out and try it today

**Comment by mattsemar** [comment]
I just uploaded a new pre-release version if you want to try it out before I release it for real

**Comment by Ximu-Luya** [comment]
OK, I am trying

**Comment by Ximu-Luya** [comment]
![image](https://user-images.githubusercontent.com/53012237/170432453-1a670311-3567-49c3-a80d-22d53bd50a28.png)
The `recipe` string above doesn't seem to be extracted. 
The title style in this window doesn't work, and some other windows have this problem too, not all.

**Comment by Ximu-Luya** [comment]
Apart from the above, there are no other problems

**Comment by mattsemar** [comment]
I'm not too sure what causes that styling issue, but it's not a new thing. Someday I'll figure it out

I just uploaded a new version with the word "Recipe" translated. I used the word that the game has in parens on the item tooltip for an alt recipe when replicator window is open: 公式, hope that works

https://github.com/mattsemar/dsp-bottleneck/releases/tag/v1.0.14-translateRev3

Is there any text from the readme you'd like to add a translation for?

**Comment by Ximu-Luya** [comment]
Of course, I hope you can help to complete the work other than the translation, and I will translate the text in it. 
I don't have much contact with open source projects. I hope you can understand and it is a pleasure to work with you.

**Comment by mattsemar** [comment]
I was thinking maybe we could just add a translation of this: https://github.com/mattsemar/dsp-bottleneck/blame/master/README.md#L3-L5 directly to the readme file

**Comment by Ximu-Luya** [comment]
Don't we need full text translation? Or add a clickable button to jump to the Chinese readme file

**Comment by mattsemar** [comment]
Oh, a link should be fine

**Comment by mattsemar** [comment]
I added a new file for the Chinese translation of the readme. I'm going to just merge the PR so the screenshot image and the link won't be broken so you can submit a new PR against master after that.
Also, this text from the main readme should be translated
```
Note: A Chinese translation of this readme can be found [here](https://github.com/mattsemar/dsp-bottleneck/blob/master/README_zhcn.md?raw=true)
```
then I think we should be good to go.

**Comment by Ximu-Luya** [comment]
OK, I will submit a pr after finishing the translation.

**Comment by mattsemar** [comment]
I'm about to leave on a trip so I'm just going to release what we have for now. I'll be on the lookout for the PR while I'm gone, though.

**Comment by Ximu-Luya** [comment]
OK, no problem. I've been a little busy recently, sorry that I can't submit a pr these days. I will submit the translation of the readme as soon as I am done.
